spring.datasource.url=jdbc:postgresql://stranger:5432/stranger
spring.datasource.username=app
spring.datasource.password=app

spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true